import Foundation

enum Arcana: String, Codable {
    case major
    case minor
}

enum Suit: String, Codable {
    case wands
    case cups
    case swords
    case pentacles
}

struct TarotCard: Identifiable, Codable {
    let id: Int
    let name: String
    let arcana: Arcana
    let suit: Suit?
    let number: String
    let uprightMeaning: String
    let reversedMeaning: String
    let keywords: [String]
    let symbolism: String
    let symbolName: String  // SF Symbol name — replaces emoji

    var suitSymbolName: String {
        switch suit {
        case .wands: return "flame"
        case .cups: return "drop.fill"
        case .swords: return "wind"
        case .pentacles: return "leaf.fill"
        case .none: return "sparkle"
        }
    }
}

// MARK: - Full 78-Card Deck

extension TarotCard {
    static let deck: [TarotCard] = majorArcana + minorArcanaWands + minorArcanaCups + minorArcanaSwords + minorArcanaPentacles

    // MARK: Major Arcana (22 cards)
    static let majorArcana: [TarotCard] = [
        TarotCard(id: 0, name: "The Fool", arcana: .major, suit: nil, number: "0",
            uprightMeaning: "You stand at the edge of a great precipice, about to leap into the unknown with nothing but trust. The Fool speaks of new beginnings, pure potential, and the sacred naivety required to begin. Every great journey starts with this single step off the cliff.",
            reversedMeaning: "A warning against recklessness disguised as courage. You may be ignoring practical concerns in favour of fantasy, or fear may be holding you back from a necessary leap. Examine which voice inside you is truly wise.",
            keywords: ["beginnings", "innocence", "spontaneity", "free spirit"],
            symbolism: "A wanderer at the cliff's edge, white rose in hand, unburdened by the weight of what he carries.",
            symbolName: "sparkle"),
        TarotCard(id: 1, name: "The Magician", arcana: .major, suit: nil, number: "I",
            uprightMeaning: "All the tools of creation lie before you — the wand of will, the cup of emotion, the sword of intellect, the pentacle of matter. The Magician says: you already possess everything needed to manifest your vision. The only question is whether you will raise your hand and direct the energy.",
            reversedMeaning: "Power is being misused or withheld. Either manipulation is at play — yours or another's — or you possess gifts you are afraid to claim. The skills are there; the will is not yet aligned.",
            keywords: ["willpower", "manifestation", "skill", "resourcefulness"],
            symbolism: "One hand points to heaven, one to earth — the bridge between divine inspiration and worldly action.",
            symbolName: "wand.and.stars"),
        TarotCard(id: 2, name: "The High Priestess", arcana: .major, suit: nil, number: "II",
            uprightMeaning: "What cannot be spoken sits behind the veil. The High Priestess guards the threshold between the visible and invisible worlds, reminding you that intuition is a form of knowing more ancient and precise than reason. Be still. Listen to what is being whispered beneath the noise.",
            reversedMeaning: "Sacred knowledge is being suppressed or withheld — perhaps by you from yourself. The subconscious is shouting through dreams, synchronicities, and physical sensation. To ignore the inner voice now is to wander in a wilderness of your own making.",
            keywords: ["intuition", "mystery", "inner knowing", "the subconscious"],
            symbolism: "Seated between twin pillars at the threshold of the temple, a scroll of hidden law resting in her lap.",
            symbolName: "moon.stars"),
        TarotCard(id: 3, name: "The Empress", arcana: .major, suit: nil, number: "III",
            uprightMeaning: "Creation in its most abundant, sensory, embodied form. The Empress presides over the fertile earth, and her energy asks you to nurture — your work, your relationships, your body. What you tend with love will bloom beyond what you imagined possible.",
            reversedMeaning: "Creative blockage or over-dependency. Either you are giving so much of yourself that the well has run dry, or you are withholding the nourishment something desperately needs. The garden grows only when the gardener is also fed.",
            keywords: ["fertility", "abundance", "nurturing", "sensuality", "nature"],
            symbolism: "A crowned mother-figure upon a throne of grain, the forest at her back, the river of life at her feet.",
            symbolName: "leaf.fill"),
        TarotCard(id: 4, name: "The Emperor", arcana: .major, suit: nil, number: "IV",
            uprightMeaning: "Authority, structure, and the wise application of power. The Emperor has built his kingdom through discipline and clear vision. He asks you to take full responsibility for your domain — to stop waiting for permission and to lead with integrity from the throne of your own life.",
            reversedMeaning: "Control has become tyranny, either externally imposed or self-inflicted. Rigidity masquerades as strength. Examine where your need for control is actually a mask for fear, and where surrendering some power might allow something more alive to emerge.",
            keywords: ["authority", "structure", "stability", "leadership"],
            symbolism: "An armored sovereign upon a stone throne, the ram-headed scepter of Aries clenched in his fist.",
            symbolName: "shield.fill"),
        TarotCard(id: 5, name: "The Hierophant", arcana: .major, suit: nil, number: "V",
            uprightMeaning: "Tradition, sacred wisdom, and the transmission of knowledge through established channels. The Hierophant calls you toward ritual, institution, and the comfort of shared belief. There is profound power in belonging to something larger than yourself.",
            reversedMeaning: "The institution has become a cage. Rules that once protected are now restricting growth, and the spirit behind the form has been forgotten. This may be a summons to forge your own path, or to question which traditions you follow from fear rather than faith.",
            keywords: ["tradition", "institution", "spiritual guidance", "conformity"],
            symbolism: "The keeper of sacred keys, seated between two acolytes, bridging the earthly and the divine through received doctrine.",
            symbolName: "key.fill"),
        TarotCard(id: 6, name: "The Lovers", arcana: .major, suit: nil, number: "VI",
            uprightMeaning: "A crossroads of the heart. The Lovers speaks not merely of romantic union but of the sacred choice between two paths — and the aligning of values that such a choice demands. When you choose love, you choose who you are becoming.",
            reversedMeaning: "Misalignment of values has created disharmony. A decision made from fear, social pressure, or external expectation rather than inner truth has left you at odds with yourself. The reconciliation required begins not outwardly but within.",
            keywords: ["love", "union", "alignment", "choice", "values"],
            symbolism: "Two figures beneath the angel of air, standing at the threshold of a decision that will define the course of their lives.",
            symbolName: "heart.fill"),
        TarotCard(id: 7, name: "The Chariot", arcana: .major, suit: nil, number: "VII",
            uprightMeaning: "Victory through disciplined will. The Chariot is not pulled by one force but by two — opposing impulses brought under the mastery of focused intention. What others call impossible, you will achieve by holding the reins of your own contradictions with steady hands.",
            reversedMeaning: "The vehicle has veered off course. Aggression without direction, ambition without wisdom, or an unacknowledged inner conflict is scattering your energy. Pause before pushing harder — you may need to redirect rather than accelerate.",
            keywords: ["victory", "willpower", "control", "determination"],
            symbolism: "A warrior-king who does not hold physical reins but commands his starry steeds through sheer concentrated will.",
            symbolName: "arrow.up.circle.fill"),
        TarotCard(id: 8, name: "Strength", arcana: .major, suit: nil, number: "VIII",
            uprightMeaning: "The lion is tamed not through force but through love. True strength is the courage to be gentle, the wisdom to be patient, and the audacity to believe that kindness is more powerful than domination. Something wild within you is waiting to be met with compassion rather than suppression.",
            reversedMeaning: "Inner weakness is being projected outward as aggression, or raw power is being turned against yourself through harsh self-criticism. The thing you are fighting hardest may simply need to be held. Shame is not strength.",
            keywords: ["courage", "patience", "compassion", "inner strength"],
            symbolism: "A woman closes the jaws of a lion with bare hands, her white garment unstained, an infinity symbol floating above her head.",
            symbolName: "flame"),
        TarotCard(id: 9, name: "The Hermit", arcana: .major, suit: nil, number: "IX",
            uprightMeaning: "The descent into solitude is not retreat but preparation. The Hermit carries a lantern to light only the next step — not the destination — because the path of genuine wisdom is walked step by solitary step. What you seek exists in the silence beneath all your busyness.",
            reversedMeaning: "Isolation has curdled into withdrawal, or you have denied yourself the solitude that genuine reflection requires. The hermit who stays too long in the cave loses touch with the world; the one who refuses to enter it never finds himself.",
            keywords: ["solitude", "introspection", "guidance", "inner wisdom"],
            symbolism: "A grey-cloaked elder atop a snow-swept mountain, holding a six-pointed lantern that illuminates one step at a time.",
            symbolName: "flashlight.on.fill"),
        TarotCard(id: 10, name: "Wheel of Fortune", arcana: .major, suit: nil, number: "X",
            uprightMeaning: "The great turning. Whatever has been fixed is now in motion; whatever was in motion is crystallising. Fortune neither punishes nor rewards — it simply cycles. Align with the wheel's turning rather than resist it, and you will ride the wave rather than be crushed beneath it.",
            reversedMeaning: "Resistance to change is creating unnecessary suffering. You cannot stop the wheel from turning, and the attempt to do so is costing you dearly. Examine what you are clinging to, and ask honestly whether holding on is wisdom or fear.",
            keywords: ["change", "cycles", "fate", "turning points"],
            symbolism: "The eternal wheel inscribed with alchemical symbols, sphinx on top, serpent falling, jackal rising — the perpetual dance of fortune.",
            symbolName: "circle.circle.fill"),
        TarotCard(id: 11, name: "Justice", arcana: .major, suit: nil, number: "XI",
            uprightMeaning: "The scales are perfectly calibrated, and the sword of discernment is raised without apology. Justice speaks of cause and consequence, of the universe's impeccable accounting. What you have sown is being reckoned. There is no escaping this truth, nor should you want to.",
            reversedMeaning: "Something is out of balance, and the imbalance is being ignored or suppressed. Legal matters may be delayed or skewed. More personally, you may be avoiding accountability for a truth you already know. Justice delayed is not justice denied — it is merely deferred.",
            keywords: ["fairness", "truth", "law", "cause and effect"],
            symbolism: "A crowned figure enthroned between twin pillars, sword raised in one hand and balanced scales in the other.",
            symbolName: "scale.3d"),
        TarotCard(id: 12, name: "The Hanged Man", arcana: .major, suit: nil, number: "XII",
            uprightMeaning: "Voluntary surrender as a spiritual act. The Hanged Man is not a victim — he chose to hang from the tree to gain the perspective that can only be found by seeing the world upside down. What feels like stagnation may be the deep gestation required for profound transformation.",
            reversedMeaning: "Sacrifice is being made in vain, or necessary release is being postponed. Either you are clinging to a martyrdom that no longer serves, or you have been suspended long enough and the time for movement has arrived. The pause has become an avoidance.",
            keywords: ["surrender", "new perspective", "pause", "sacrifice"],
            symbolism: "A serene figure hanging from one foot on a living tree, the halo of enlightenment encircling his head.",
            symbolName: "arrow.down.circle"),
        TarotCard(id: 13, name: "Death", arcana: .major, suit: nil, number: "XIII",
            uprightMeaning: "The card most misread in all the tarot. Death does not speak of physical death but of transformation so complete that what comes after cannot recognise what came before. A chapter is closing — not as punishment but as permission. What the cosmos removes, it removes to make room for what is truly yours.",
            reversedMeaning: "Resistance to necessary change is creating stagnation. You are refusing to let something die that has already ceased to live — holding form around something hollow. The suffering is not in the ending but in the prolonged refusal to end it.",
            keywords: ["transformation", "endings", "transition", "change"],
            symbolism: "A skeleton knight on a pale horse carries a black flag blooming with a white rose — death bearing the seed of rebirth.",
            symbolName: "leaf.arrow.triangle.circlepath"),
        TarotCard(id: 14, name: "Temperance", arcana: .major, suit: nil, number: "XIV",
            uprightMeaning: "The alchemy of balance. Temperance pours from vessel to vessel with perfect patience, blending opposing forces into something neither could become alone. Moderation here is not compromise but the highest art — the finding of the middle way that transcends both extremes.",
            reversedMeaning: "Imbalance and excess are disrupting the flow. Something in your life is operating in extreme: too much or too little of a vital substance. The pendulum has swung too far, and recalibration requires pausing to locate the centre point before moving again.",
            keywords: ["balance", "patience", "moderation", "alchemy"],
            symbolism: "An angelic figure stands with one foot in water and one on land, pouring light between two golden cups.",
            symbolName: "drop.fill"),
        TarotCard(id: 15, name: "The Devil", arcana: .major, suit: nil, number: "XV",
            uprightMeaning: "The chains are loose around the necks of those who stand before the horned figure — they could remove them at any time. The Devil reveals the bondage of addiction, materialism, and unconscious patterns. The first step toward freedom is simply recognising what holds you and acknowledging your own complicity.",
            reversedMeaning: "Release from bondage is beginning, or you are on the precipice of breaking free from a pattern that has enslaved you. What seemed immovable is loosening. Do not mistake this stirring for failure — it is the first breath of liberation.",
            keywords: ["bondage", "addiction", "materialism", "shadow self"],
            symbolism: "Two chained figures who could free themselves at any moment stand before the shadow-aspect of all they have surrendered to.",
            symbolName: "link"),
        TarotCard(id: 16, name: "The Tower", arcana: .major, suit: nil, number: "XVI",
            uprightMeaning: "The lightning that strikes the tower destroys only what was built on false foundations. Sudden upheaval, revelation, collapse — these are not the cosmos's cruelty but its most efficient mercy. What the Tower demolishes was never what you truly needed. Build again, but this time, build on truth.",
            reversedMeaning: "You are either in the aftermath of a Tower moment, slowly rebuilding, or you are resisting an inevitable collapse that would ultimately liberate you. Delaying the necessary destruction only increases the energy that must eventually be released.",
            keywords: ["upheaval", "sudden change", "revelation", "liberation"],
            symbolism: "A lightning-struck tower atop a rocky peak, crown blown free, figures falling through the dark air.",
            symbolName: "bolt.fill"),
        TarotCard(id: 17, name: "The Star", arcana: .major, suit: nil, number: "XVII",
            uprightMeaning: "After the Tower's devastation, the Star appears as a promise whispered in the dark: you are held, you are seen, you will be restored. The naked figure pours healing water onto parched earth. Hope here is not naivety — it is the most radical act available after everything has been stripped away.",
            reversedMeaning: "The channel to hope has been blocked by disappointment or despair. You may have lost faith in yourself or in something larger. Rebuilding trust takes time, and the star still shines even when it cannot be seen through the clouds.",
            keywords: ["hope", "renewal", "healing", "inspiration"],
            symbolism: "A nude figure kneels at the waters of renewal beneath a sky of eight-pointed stars, pouring forth the waters of hope.",
            symbolName: "star.fill"),
        TarotCard(id: 18, name: "The Moon", arcana: .major, suit: nil, number: "XVIII",
            uprightMeaning: "The path is illuminated only dimly, and something in the depths is stirring. The Moon speaks of illusion, the subconscious, and the fertile uncertainty of not yet knowing. What appears as shadow may be projection; what appears as monster may be the face of your own unmet need.",
            reversedMeaning: "A confusion or deception is beginning to clear. The veil is thinning; the distortions of fear and projection are being seen for what they are. Or, suppressed emotions are demanding expression before clarity can arrive.",
            keywords: ["illusion", "the unconscious", "fear", "confusion", "dreams"],
            symbolism: "A full moon between twin towers, a lobster emerging from the primordial waters, wolf and dog howling at what they cannot reach.",
            symbolName: "moon.fill"),
        TarotCard(id: 19, name: "The Sun", arcana: .major, suit: nil, number: "XIX",
            uprightMeaning: "Full illumination, unambiguous joy, and the radiant confidence of a child riding naked through a sunflower field with nothing to hide and nothing to fear. The Sun burns away every shadow, every pretence, every unnecessary complexity. What remains in this light is simply: you, alive and enough.",
            reversedMeaning: "Joy is being blocked or dimmed — perhaps by perfectionism, self-doubt, or the fear of being fully seen. The sun has not stopped shining; something is obscuring your access to it. What small thing could you do today to step into the light?",
            keywords: ["joy", "success", "clarity", "vitality", "confidence"],
            symbolism: "A gleaming child upon a white horse beneath an enormous sun, the sunflowers behind turning their faces in adoration.",
            symbolName: "sun.max.fill"),
        TarotCard(id: 20, name: "Judgement", arcana: .major, suit: nil, number: "XX",
            uprightMeaning: "The great calling. An angel sounds a trumpet and the dead rise from their graves — not in terror but in answer. Judgement is the moment when everything you have been becomes crystallised into who you truly are. The call is sounding now. Will you rise to answer it?",
            reversedMeaning: "Self-judgement has become self-condemnation. You are holding yourself to a verdict that is either incorrect or that you are refusing to release even after the sentence has been served. Forgiveness is not the erasure of consequence — it is the permission to stop being punished.",
            keywords: ["reckoning", "awakening", "rebirth", "absolution"],
            symbolism: "An archangel's trumpet sounds over coffins opening to the sea, figures rising with arms spread wide in total surrender.",
            symbolName: "bell.fill"),
        TarotCard(id: 21, name: "The World", arcana: .major, suit: nil, number: "XXI",
            uprightMeaning: "Completion. Not the end but the integration — the moment when the journey becomes the destination and the self becomes the world it was travelling through. A cycle of profound learning closes here with grace. Receive this arrival fully before the next journey begins.",
            reversedMeaning: "Something is preventing completion — a loose end, an unacknowledged lesson, or a fear of the closure that comes with real achievement. The finish line is visible but a part of you holds back from crossing it. What would it mean to actually be done?",
            keywords: ["completion", "integration", "achievement", "wholeness"],
            symbolism: "A dancing figure wrapped in a purple banner within a laurel wreath, the four living creatures of the elements at each corner.",
            symbolName: "circle.hexagongrid.fill")
    ]

    // MARK: Minor Arcana — Wands (14 cards)
    static let minorArcanaWands: [TarotCard] = [
        TarotCard(id: 22, name: "Ace of Wands", arcana: .minor, suit: .wands, number: "Ace",
            uprightMeaning: "A hand emerges from a cloud holding a living branch that is already sprouting new growth. The spark of creative inspiration has been placed in your hand — the question is not whether you have the idea but whether you have the courage to act on it now, before the moment passes.",
            reversedMeaning: "Creative energy is blocked, misdirected, or burning out before it can ignite anything real. The spark is present but the conditions are not yet right, or you are spreading the flame too thin to sustain combustion.",
            keywords: ["inspiration", "creative spark", "new venture", "passion"],
            symbolism: "A single living wand extended from a divine hand through storm clouds, crackling with unrealised potential.",
            symbolName: "flame"),
        TarotCard(id: 23, name: "Two of Wands", arcana: .minor, suit: .wands, number: "2",
            uprightMeaning: "You stand on the parapet with the world literally in your hands, surveying the territory that awaits conquest. The decision between the known and the unknown stretches before you. This is the card of the planner, the visionary, the one who sees not what is but what could be.",
            reversedMeaning: "Hesitation or fear of the unknown is keeping you tethered to what is familiar but limiting. The world in your hand grows heavy from being held rather than explored. The plan you keep refining may be a way of avoiding the risk of actually beginning.",
            keywords: ["planning", "vision", "bold decisions", "future"],
            symbolism: "A figure atop a castle battlement, holding a globe, gazing across the open sea toward lands not yet reached.",
            symbolName: "flame"),
        TarotCard(id: 24, name: "Three of Wands", arcana: .minor, suit: .wands, number: "3",
            uprightMeaning: "The ships have sailed and the merchant watches them crest the horizon with quiet confidence. The Three of Wands says your plans are in motion, your foundations are solid, and the returns are coming. You have done what you needed to do — now trust the current to carry it forward.",
            reversedMeaning: "Delays and setbacks are testing the faith you placed in your plans. Something launched is taking longer than expected, or the expansion you anticipated has been blocked. Patience is required, but so is an honest assessment of whether the venture is viable.",
            keywords: ["expansion", "foresight", "enterprise", "patience"],
            symbolism: "A solitary figure overlooking the sea from a high cliff, three planted wands at his back, ships visible on the far horizon.",
            symbolName: "flame"),
        TarotCard(id: 25, name: "Four of Wands", arcana: .minor, suit: .wands, number: "4",
            uprightMeaning: "The harvest festival, the homecoming, the moment of earned celebration. Four wands stand garlanded with flowers and fruit — the structure of effort supporting the decoration of joy. Pause here and let yourself be glad. Not every milestone needs to be rushed past on the way to the next.",
            reversedMeaning: "Celebration is being delayed or disrupted, possibly by internal restlessness or external instability in the home environment. The foundations of security may need attention before joy can take root without anxiety.",
            keywords: ["celebration", "homecoming", "harmony", "community"],
            symbolism: "Two figures dance beneath a floral canopy supported by four wands, a castle of belonging visible in the background.",
            symbolName: "flame"),
        TarotCard(id: 26, name: "Five of Wands", arcana: .minor, suit: .wands, number: "5",
            uprightMeaning: "Five young men clash wands in a scrimmage that looks chaotic but may simply be the healthy competition of equals pushing each other to improve. The conflict here is energetic rather than malicious — yet it is still costing energy that could be redirected if the parties could find alignment.",
            reversedMeaning: "Conflict is either being avoided to keep a false peace, or it is degenerating into genuine hostility. The scrimmage has either ended or become a real fight. Clarity about which is happening is the first step toward resolution.",
            keywords: ["conflict", "competition", "chaos", "scattered energy"],
            symbolism: "Five youths with raised wands in apparent contest — neither clearly winning, all equally committed to the struggle.",
            symbolName: "flame"),
        TarotCard(id: 27, name: "Six of Wands", arcana: .minor, suit: .wands, number: "6",
            uprightMeaning: "The victory parade. A crowned rider moves through a crowd of admirers, and the laurel wreath on the wand confirms: this triumph is real, it was earned, and it is being witnessed. Let yourself be seen in your success — receiving recognition is not vanity but the natural completion of the cycle of effort.",
            reversedMeaning: "The recognition you sought has not arrived, or victory has come without the acknowledgment you needed to make it feel real. The crowd is silent. Examine whether the validation was necessary, and whether the achievement holds meaning in its own right.",
            keywords: ["victory", "recognition", "achievement", "public success"],
            symbolism: "A triumphant rider on a white horse bears a laurel wreath aloft, accompanied by a procession of supporters.",
            symbolName: "flame"),
        TarotCard(id: 28, name: "Seven of Wands", arcana: .minor, suit: .wands, number: "7",
            uprightMeaning: "You have claimed the high ground and they are coming for it. The Seven of Wands calls for the courage to defend what you have built, to hold your position against the critics, challengers, and competitors who see your advantage as something to be taken. Advantageous positions require active defence.",
            reversedMeaning: "You are overwhelmed by opposition or have surrendered a position you should have defended. The challenge has made you doubt what you once stood firmly for. Or conversely, you are being defensively aggressive in situations that do not actually threaten you.",
            keywords: ["defence", "perseverance", "challenge", "conviction"],
            symbolism: "A figure on high ground holds his wand against six others thrust upward from below — the cost of holding the summit.",
            symbolName: "flame"),
        TarotCard(id: 29, name: "Eight of Wands", arcana: .minor, suit: .wands, number: "8",
            uprightMeaning: "Eight wands fly through the open sky without obstruction — this is the card of swift action, rapid communication, and momentum unencumbered by doubt. What has been stalled suddenly moves. The message arrives. The journey begins. Do not stand in the way of your own velocity.",
            reversedMeaning: "Movement is being blocked or has become chaotic and misdirected. Communications are crossed, plans are falling apart, or speed has become haste that creates more problems than it solves. Slow down enough to reorient before the speed increases again.",
            keywords: ["speed", "momentum", "communication", "swift action"],
            symbolism: "Eight parallel wands sail across a clear sky toward a green landscape — pure directed motion with nothing to impede it.",
            symbolName: "flame"),
        TarotCard(id: 30, name: "Nine of Wands", arcana: .minor, suit: .wands, number: "9",
            uprightMeaning: "Wounded but undefeated. The weary guardian leans on his wand, eight more standing behind him, having endured battle after battle. The resilience of this card is not the buoyancy of the untested but the harder, deeper steadfastness of the one who has seen difficulty and chosen to stand regardless.",
            reversedMeaning: "Stubbornness has replaced resilience. You have fought so long that fighting has become an identity, and you are now defending positions that no longer need defending. Or exhaustion has finally overwhelmed the will, and rest is not defeat but survival.",
            keywords: ["resilience", "perseverance", "courage", "close to the goal"],
            symbolism: "A battered sentinel stands guard before eight upright wands, head bandaged, eyes alert — the look of one who has survived what should have broken them.",
            symbolName: "flame"),
        TarotCard(id: 31, name: "Ten of Wands", arcana: .minor, suit: .wands, number: "10",
            uprightMeaning: "The figure is almost bent double beneath the ten wands he carries, yet the destination is visible just ahead. The Ten of Wands speaks of taking on too much and the burning need to either distribute the burden or set some of it down. The strength to carry is admirable; the wisdom to delegate is mastery.",
            reversedMeaning: "The burden has become unbearable, and either collapse is imminent or relief is finally arriving through the willingness to let go of unnecessary weight. Some of what you carry was never yours to carry. Asking for help is not weakness — it is the prerequisite of sustainability.",
            keywords: ["burden", "responsibility", "overextension", "duty"],
            symbolism: "A figure struggles forward, nearly obscured by the ten wands piled in his arms, the distant village home tantalizingly close.",
            symbolName: "flame"),
        TarotCard(id: 32, name: "Page of Wands", arcana: .minor, suit: .wands, number: "Page",
            uprightMeaning: "A young explorer holds a wand and gazes at a distant landscape with pure, unfiltered enthusiasm. The Page of Wands brings news of adventure, the energy of pure possibility, and the permission to approach something entirely new with beginners' mind — to explore without needing to be expert.",
            reversedMeaning: "Enthusiasm has outpaced follow-through, or someone's energy is all spark and no sustained flame. Big announcements are being made that may not be backed by real commitment. Alternatively, creative fire is being extinguished by timidity or lack of confidence.",
            keywords: ["enthusiasm", "exploration", "free spirit", "news"],
            symbolism: "A youthful figure in a patterned tunic holds a sprouting wand, gazing toward the desert horizon with undimmed curiosity.",
            symbolName: "flame"),
        TarotCard(id: 33, name: "Knight of Wands", arcana: .minor, suit: .wands, number: "Knight",
            uprightMeaning: "The fire of pure adventure made mobile. The Knight of Wands charges without hesitation, driven by passion and the intoxicating energy of forward motion. He is magnificent in his daring — and will need to cultivate patience and forethought to fully realise the greatness that burns within him.",
            reversedMeaning: "Impulsiveness has become recklessness. The charge has started before the target was properly identified, and now there is momentum without direction. Or the fire has been dampened by obstacles, and frustration is expressing itself as aggression.",
            keywords: ["action", "adventure", "impulsiveness", "confidence"],
            symbolism: "A flame-adorned knight on a rearing horse, wand raised, charging through a desert landscape without looking back.",
            symbolName: "flame"),
        TarotCard(id: 34, name: "Queen of Wands", arcana: .minor, suit: .wands, number: "Queen",
            uprightMeaning: "She holds the sunflower in one hand and the wand in the other — the integration of warmth and will, creativity and confidence. The Queen of Wands is magnetically attractive because she has made peace with her own fire. She leads by inspiring rather than demanding, and the black cat at her feet speaks of magic that serves her.",
            reversedMeaning: "The flame has turned inward as jealousy or manipulation, or the confidence has curdled into arrogance. The Queen's warmth can become possessiveness; her boldness can become dominance. Examine where your fire is burning for yourself and where it is burning at others.",
            keywords: ["courage", "confidence", "passion", "charisma"],
            symbolism: "A bold queen upon a throne adorned with lions and sunflowers, a black cat at her feet, the wand of authority in her sure grip.",
            symbolName: "flame"),
        TarotCard(id: 35, name: "King of Wands", arcana: .minor, suit: .wands, number: "King",
            uprightMeaning: "Visionary leadership born from the marriage of ambition and integrity. The King of Wands has mastered the raw energy of fire and shaped it into purposeful direction. He does not simply dream — he builds the infrastructure for dreams to become real, and inspires those around him to bring their best to the endeavour.",
            reversedMeaning: "Power is being wielded arrogantly or impulsively. The King's fire has become domineering, his confidence has closed off to counsel, and his vision has become an ego project rather than a genuine mission. Leadership without humility eventually empties the room.",
            keywords: ["leadership", "vision", "boldness", "mastery"],
            symbolism: "A leonine king upon a wand-carved throne, a salamander crawling at his foot, his gaze fixed on horizons yet to be reached.",
            symbolName: "flame")
    ]

    // MARK: Minor Arcana — Cups (14 cards)
    static let minorArcanaCups: [TarotCard] = [
        TarotCard(id: 36, name: "Ace of Cups", arcana: .minor, suit: .cups, number: "Ace",
            uprightMeaning: "A chalice overflowing with the waters of emotional abundance, offered by a divine hand from the clouds. The Ace of Cups is an invitation to open your heart — to love, to be loved, to create, to feel without the armour that has protected you long past the point of necessity.",
            reversedMeaning: "Emotional blockage or the overflow of repressed feeling. Either the heart has closed against love and connection, or old wounds are preventing the clean reception of what is being offered. The cup is full but the hands refuse to hold it.",
            keywords: ["love", "new relationship", "emotional beginning", "intuition"],
            symbolism: "A golden chalice overflows with five streams of water, a dove descending with a communion wafer in its beak.",
            symbolName: "drop.fill"),
        TarotCard(id: 37, name: "Two of Cups", arcana: .minor, suit: .cups, number: "2",
            uprightMeaning: "Two people face each other and raise their cups in mutual recognition. This is the card of partnership — romantic, business, or deep friendship — built on genuine equality and the recognition of something sacred in the other. What you see in them is also what they see in you.",
            reversedMeaning: "A partnership is out of balance or breaking down. The mutual regard has curdled into codependency, competition, or the subtle resentment of unacknowledged imbalance. What needs to be said between two people is being left in silence.",
            keywords: ["partnership", "union", "attraction", "connection"],
            symbolism: "Two figures exchange cups beneath the caduceus of Mercury topped by a winged lion — the symbol of a bond sealed with mutual intention.",
            symbolName: "drop.fill"),
        TarotCard(id: 38, name: "Three of Cups", arcana: .minor, suit: .cups, number: "3",
            uprightMeaning: "Three women dance in a circle, arms raised in shared celebration of the harvest. The Three of Cups is the joy of friendship, sisterhood, and community — the specific pleasure of being known and delighted in by others who see your true self. Let yourself be celebrated, and celebrate in return.",
            reversedMeaning: "Social overindulgence, gossip, or the exclusion of someone from the inner circle. The celebration has become cliquish, or excess has led to regret. Alternatively, social withdrawal is denying you the nourishment that only community can provide.",
            keywords: ["friendship", "celebration", "community", "joy"],
            symbolism: "Three crowned women lift cups in a joyful dance surrounded by the abundance of a fertile autumn harvest.",
            symbolName: "drop.fill"),
        TarotCard(id: 39, name: "Four of Cups", arcana: .minor, suit: .cups, number: "4",
            uprightMeaning: "A figure sits beneath a tree, arms crossed, staring at three cups on the ground while a fourth — offered by a divine hand — goes unnoticed. The Four of Cups speaks of contemplation that has become apathy, of being so inward-turned that what is being offered cannot be received.",
            reversedMeaning: "Emerging from a period of withdrawal and introspection with renewed clarity and openness. The inward phase has served its purpose, and you are now ready to engage with what life is offering. A gift you previously dismissed is being reconsidered.",
            keywords: ["apathy", "introspection", "missed opportunities", "contemplation"],
            symbolism: "A meditative figure under a gnarled tree ignores three earthly cups while a glowing cup is extended from a cloud — unseen.",
            symbolName: "drop.fill"),
        TarotCard(id: 40, name: "Five of Cups", arcana: .minor, suit: .cups, number: "5",
            uprightMeaning: "A cloaked figure stares at three spilled cups, back turned to the two that remain full. The Five of Cups speaks of the grief that becomes fixation — the loss that consumes so completely that what remains whole cannot be acknowledged. Mourn what was lost, then turn and see what still stands.",
            reversedMeaning: "You are beginning to turn away from grief and toward what remains. The healing has begun, or you are finally allowing yourself to feel a loss that was previously suppressed. The full cups have been noticed, and the bridge back toward life is becoming visible.",
            keywords: ["grief", "loss", "regret", "acceptance"],
            symbolism: "A black-cloaked figure mourns over spilled cups, wholly blind to the two upright ones behind, a bridge to safety nearby.",
            symbolName: "drop.fill"),
        TarotCard(id: 41, name: "Six of Cups", arcana: .minor, suit: .cups, number: "6",
            uprightMeaning: "A child offers a cup of white flowers to a smaller child in a scene of pure innocence and simple gift-giving. The Six of Cups speaks of nostalgia, childhood memories, and the healing power of returning to what was simple and good in the past — without being trapped there.",
            reversedMeaning: "Nostalgia has become a retreat from present reality, or the innocence of the past is being seen through an idealising filter that prevents honest assessment. Alternatively, old wounds from childhood are surfacing and demanding attention they were never given.",
            keywords: ["nostalgia", "childhood", "innocence", "kindness"],
            symbolism: "Two children in a flower-filled courtyard exchange a cup of white blooms — a moment of pure, uncomplicated generosity.",
            symbolName: "drop.fill"),
        TarotCard(id: 42, name: "Seven of Cups", arcana: .minor, suit: .cups, number: "7",
            uprightMeaning: "Seven cups float in a dreamlike cloud, each containing a different vision — treasure, victory, beauty, truth, dragon, castle, laurel wreath. The Seven of Cups is the seduction of unlimited possibility. Until a single cup is chosen and committed to, all remains fantasy. What are you actually willing to pursue?",
            reversedMeaning: "The fog of confusion is beginning to clear, or you are making a decisive choice after a long period of paralysis. Alternatively, disillusionment has arrived as the fantasies prove unsatisfying — not as failure but as the necessary step toward authentic desire.",
            keywords: ["fantasy", "illusion", "choices", "wishful thinking"],
            symbolism: "A silhouetted figure contemplates seven glowing cups floating in cloud, each containing a different temptation or dream.",
            symbolName: "drop.fill"),
        TarotCard(id: 43, name: "Eight of Cups", arcana: .minor, suit: .cups, number: "8",
            uprightMeaning: "The figure turns and walks away from eight carefully arranged cups at the foot of a cliff and begins the climb. The Eight of Cups is one of the most courageous cards in the deck: the willingness to leave what is comfortable but no longer nourishing in search of something deeper and more true.",
            reversedMeaning: "Fear of loss is preventing a necessary departure. You are staying in a situation that has run its course because the unknown feels more frightening than the known emptiness. Or, you have abandoned something prematurely and must return to complete what was left unfinished.",
            keywords: ["walking away", "searching for truth", "withdrawal", "disillusionment"],
            symbolism: "A cloaked wanderer crosses a river by moonlight, departing eight neatly stacked cups without a backward glance.",
            symbolName: "drop.fill"),
        TarotCard(id: 44, name: "Nine of Cups", arcana: .minor, suit: .cups, number: "9",
            uprightMeaning: "The wish card. The contented figure sits before nine full cups arranged like a trophy cabinet, arms crossed in satisfaction. The Nine of Cups says: what you have wished for is coming, or already arrived. Let yourself feel the satisfaction fully rather than immediately reaching for the next desire.",
            reversedMeaning: "Satisfaction has become complacency, or fulfilment has arrived but cannot be felt because something internal prevents enjoyment. Alternatively, a wish has been granted but has not brought the joy anticipated — the question of what you truly want deserves revisiting.",
            keywords: ["contentment", "satisfaction", "wishes fulfilled", "gratitude"],
            symbolism: "A plump, well-dressed figure sits with arms crossed before nine golden cups — the portrait of a man whose wishes have come true.",
            symbolName: "drop.fill"),
        TarotCard(id: 45, name: "Ten of Cups", arcana: .minor, suit: .cups, number: "10",
            uprightMeaning: "A couple stands with arms raised beneath a rainbow of ten cups as two children dance on the green hillside of a home they have created together. The Ten of Cups is the realisation of emotional fulfilment — not the perfect life but the deeply good one, built with love and intention.",
            reversedMeaning: "The appearance of happiness masks internal disconnection. The family picture is complete, but the relationships within the frame have become strained, distant, or performative. What would it mean to tend to the actual feeling rather than the picture?",
            keywords: ["family", "happiness", "fulfilment", "harmony"],
            symbolism: "A couple and their dancing children beneath a rainbow of ten cups — the image of love made into a life.",
            symbolName: "drop.fill"),
        TarotCard(id: 46, name: "Page of Cups", arcana: .minor, suit: .cups, number: "Page",
            uprightMeaning: "A young dreamer holds a cup from which a small fish pops up to greet him, and instead of being startled, he gazes at it with fond curiosity. The Page of Cups brings messages from the unconscious, the beginning of emotional sensitivity, and the willingness to be surprised by feeling.",
            reversedMeaning: "Emotional immaturity is complicating a situation, or creative ideas are being blocked by a fear of ridicule. The sensitivity that could be a gift is being weaponised as moodiness, or the dreaming has become a way of avoiding emotional reality.",
            keywords: ["creativity", "intuition", "sensitivity", "messages"],
            symbolism: "A flower-adorned youth holds a golden cup from which a fish emerges to speak — the emissary of the dreaming world.",
            symbolName: "drop.fill"),
        TarotCard(id: 47, name: "Knight of Cups", arcana: .minor, suit: .cups, number: "Knight",
            uprightMeaning: "The romantic arrives on a calm horse with a message he will not hesitate to deliver. The Knight of Cups is moved by beauty, inspired by idealism, and willing to follow feeling wherever it leads. This is the card of the poet, the one who speaks from the heart even when the heart speaks awkward things.",
            reversedMeaning: "Romanticism has slid into moodiness, manipulation, or the intoxication of feeling without the discipline to act on it. The knight is unhorsed by emotion — swept along by feeling he cannot steer, or using sensitivity as a tool of passive aggression.",
            keywords: ["romance", "idealism", "charm", "following the heart"],
            symbolism: "A knight in ornate armor moves peacefully across a landscape, cup held forward like an offering or a herald's seal.",
            symbolName: "drop.fill"),
        TarotCard(id: 48, name: "Queen of Cups", arcana: .minor, suit: .cups, number: "Queen",
            uprightMeaning: "She holds a closed cup and does not look into it — she already knows what it contains because she knows herself with such profound intimacy that the unconscious holds no more surprises. The Queen of Cups is the master of emotional intelligence, the one whose compassion is boundless because it begins with radical self-understanding.",
            reversedMeaning: "Emotional depths have become an ocean to drown in rather than to navigate. Compassion has collapsed into codependency; sensitivity has become manipulation. The inner world is consuming the ability to function in the outer one.",
            keywords: ["compassion", "emotional intelligence", "intuition", "sensitivity"],
            symbolism: "A queen with a highly ornate covered cup sits enthroned where land meets sea — the border between the conscious and the deep.",
            symbolName: "drop.fill"),
        TarotCard(id: 49, name: "King of Cups", arcana: .minor, suit: .cups, number: "King",
            uprightMeaning: "He sits on his throne in the middle of a turbulent sea without being disturbed by it. The King of Cups has mastered the emotional realm not by suppressing feeling but by feeling everything fully while remaining the stable centre around which others can find their equilibrium. This is emotional authority at its highest expression.",
            reversedMeaning: "Emotional manipulation or the cold withdrawal that masquerades as calm. The waters have become too much, and numbing has replaced mastery. Or sensitivity is being weaponised as volatility — the sea throne is tipping.",
            keywords: ["emotional mastery", "diplomacy", "wisdom", "compassion"],
            symbolism: "A crowned king holds scepter and cup while seated on a stone throne in the midst of a churning sea, entirely unperturbed.",
            symbolName: "drop.fill")
    ]

    // MARK: Minor Arcana — Swords (14 cards)
    static let minorArcanaSwords: [TarotCard] = [
        TarotCard(id: 50, name: "Ace of Swords", arcana: .minor, suit: .swords, number: "Ace",
            uprightMeaning: "A sword thrust through a crown of laurel and palm — the sharp instrument of truth held aloft by a divine hand. The Ace of Swords cuts through confusion, illusion, and comfortable lies. This is the moment of absolute clarity, however uncomfortable its arrival. The truth has arrived. Receive it.",
            reversedMeaning: "Mental confusion, unclear thinking, or a truth that cannot yet be received because the conditions for its reception are not ready. A sword drawn too early can do more damage than good. Ensure you have the full picture before you cut.",
            keywords: ["clarity", "truth", "breakthrough", "intellect"],
            symbolism: "A divine hand extends a double-edged sword through storm clouds — pure intellect emerging from the turmoil of confusion.",
            symbolName: "wind"),
        TarotCard(id: 51, name: "Two of Swords", arcana: .minor, suit: .swords, number: "2",
            uprightMeaning: "A blindfolded figure holds two swords crossed before her heart, refusing to look at a turbulent sea behind her. The Two of Swords speaks of the temporary peace of willful not-knowing — the stalemate maintained by choosing not to choose. The blindfold is self-imposed; the decision must eventually be made.",
            reversedMeaning: "The blindfold is coming off, and the difficult truth can no longer be avoided. A stalemate is breaking — either through external force or through the courage to finally look. The discomfort of decision is preferable to the slow erosion of perpetual avoidance.",
            keywords: ["stalemate", "indecision", "avoidance", "blocked perception"],
            symbolism: "A blindfolded woman sits with two crossed swords before a crescent-lit sea, perfectly balanced in her refusal to see.",
            symbolName: "wind"),
        TarotCard(id: 52, name: "Three of Swords", arcana: .minor, suit: .swords, number: "3",
            uprightMeaning: "Three swords pierce a red heart suspended in a storming sky. The Three of Swords is grief without euphemism — the card of heartbreak, betrayal, and the pain that cannot be reasoned away. It says: this hurts. Let it hurt. The pierced heart is still beating, which means it is still alive.",
            reversedMeaning: "Recovery from grief is beginning, or old pain is surfacing after long suppression. Either the heart is beginning to heal and the swords are slowly withdrawing, or a wound that was never properly cleaned is finally being acknowledged and tended.",
            keywords: ["heartbreak", "grief", "sorrow", "betrayal"],
            symbolism: "Three swords pierce a floating heart in the middle of a storm — no hand, no reason, no comfort — just the fact of pain.",
            symbolName: "wind"),
        TarotCard(id: 53, name: "Four of Swords", arcana: .minor, suit: .swords, number: "4",
            uprightMeaning: "A knight lies on a tomb in effigy, hands in prayer, three swords on the wall above him and one beneath — not dead but at absolute rest. The Four of Swords is the sacred prescription of rest after struggle. You cannot fight from an empty vessel. The mind requires silence to integrate what it has experienced.",
            reversedMeaning: "Rest is being resisted, or you are emerging from recovery before you are fully restored. The forced inactivity of illness, burnout, or circumstances may be the body's demand for what was refused voluntarily. Or recuperation is almost complete and the return to activity approaches.",
            keywords: ["rest", "recovery", "meditation", "sanctuary"],
            symbolism: "An effigy-knight lies in serene contemplation on a church tomb, swords above and below, the stained glass illuminating peace.",
            symbolName: "wind"),
        TarotCard(id: 54, name: "Five of Swords", arcana: .minor, suit: .swords, number: "5",
            uprightMeaning: "A smirking figure collects three swords while two defeated opponents retreat into a darkening sky. Winning this conflict has cost you their trust and dignity. The Five of Swords asks whether the victory was worth what it required. Some battles, once won, leave the victor emptier than the defeated.",
            reversedMeaning: "The aftermath of a bitter conflict and the beginning of reconciliation. Or the refusal to let go of a grievance long after the conflict has ended. The swords are down, but someone is still collecting them as trophies instead of letting the matter rest.",
            keywords: ["conflict", "defeat", "hollow victory", "tension"],
            symbolism: "A triumphant figure with three claimed swords watches two defeated figures walk away into a stormy sky.",
            symbolName: "wind"),
        TarotCard(id: 55, name: "Six of Swords", arcana: .minor, suit: .swords, number: "6",
            uprightMeaning: "A boatman ferries a cloaked figure and child across still water. The six swords stand upright in the bow of the boat — carried but no longer in use. The Six of Swords is the mercy of forward motion after difficulty: a slow crossing toward calmer waters. You are moving in the right direction, even if the journey feels somber.",
            reversedMeaning: "The crossing is being resisted or delayed. A transition that needs to happen cannot move forward because of unfinished business, unprocessed grief, or the fear of what lies on the far shore. The boat is stuck at the bank.",
            keywords: ["transition", "moving on", "leaving behind", "healing journey"],
            symbolism: "A silent boatman crosses gray water carrying a cloaked woman and child, six swords planted at the bow like mementos of battles past.",
            symbolName: "wind"),
        TarotCard(id: 56, name: "Seven of Swords", arcana: .minor, suit: .swords, number: "7",
            uprightMeaning: "A figure sneaks away from a military camp carrying five swords, leaving two behind. The Seven of Swords speaks of strategy, stealth, and the calculated move — but also of the ethics of such maneuvering. Is the cleverness being used to survive a difficult situation, or is it deception dressed as intelligence?",
            reversedMeaning: "A deception is being uncovered, or a secret you have been carrying is ready to be confessed. The hidden maneuvering is no longer sustainable. Or, you are returning to restore what was taken — the first steps toward integrity after a period of compromise.",
            keywords: ["strategy", "deception", "cunning", "evasion"],
            symbolism: "A figure tiptoes away from a camp bearing five swords, looking back furtively, leaving two planted in the ground behind.",
            symbolName: "wind"),
        TarotCard(id: 57, name: "Eight of Swords", arcana: .minor, suit: .swords, number: "8",
            uprightMeaning: "A bound and blindfolded figure stands surrounded by eight swords — yet the bonds are loose, the blindfold self-imposed, and the path away is clear. The Eight of Swords is the prison of limiting belief, the trap that exists primarily in perception. The first step is recognising that the cage door is open.",
            reversedMeaning: "The mental prison is beginning to crack. You are starting to see the self-imposed nature of your limitations, or external restrictions are finally loosening. The swords are being pulled from the ground of your consciousness one by one.",
            keywords: ["restriction", "limiting beliefs", "imprisonment", "powerlessness"],
            symbolism: "A blindfolded woman stands lightly bound amid eight encircling swords — contained not by the swords but by her belief in them.",
            symbolName: "wind"),
        TarotCard(id: 58, name: "Nine of Swords", arcana: .minor, suit: .swords, number: "9",
            uprightMeaning: "A figure sits bolt upright in bed, head in hands, nine swords arrayed on the dark wall above. The Nine of Swords is the 3am card — the anxious mind that turns everything into disaster, the thoughts that spiral in the dark. The suffering here is real, even when the fears are not. What would it mean to be kind to the frightened self?",
            reversedMeaning: "The worst of the anxiety is passing, or what seemed catastrophic is proving to be manageable. Or, suppressed despair is finally surfacing to be acknowledged and released rather than swallowed again. The night is darkest before the breaking of the day.",
            keywords: ["anxiety", "nightmares", "despair", "mental anguish"],
            symbolism: "A figure wakes in the night seized by dread, nine swords looming above in the darkness — the architecture of an anxious mind.",
            symbolName: "wind"),
        TarotCard(id: 59, name: "Ten of Swords", arcana: .minor, suit: .swords, number: "10",
            uprightMeaning: "A figure lies face down on a barren plain with ten swords in his back. The sky is dark behind him — but the horizon ahead is beginning to glow with dawn. The Ten of Swords says: this ending is absolute, it is painful, and it is also complete. Nothing can make it worse. The only direction now is forward and up.",
            reversedMeaning: "Recovery is beginning from a painful ending, or you are resisting the final surrender that would allow the healing to start. Something must be fully relinquished before the resurrection can occur. The dawn is there — but first, the lying down.",
            keywords: ["painful ending", "loss", "crisis", "defeat"],
            symbolism: "Ten swords pierce a prone figure on a dark plain — yet the distant horizon glows with the unmistakable light of dawn.",
            symbolName: "wind"),
        TarotCard(id: 60, name: "Page of Swords", arcana: .minor, suit: .swords, number: "Page",
            uprightMeaning: "A young figure stands on a hilltop in a windswept landscape, sword raised with eager curiosity. The Page of Swords brings quick intelligence, intellectual curiosity, and the restless desire to know and to communicate. News arrives. Questions are being asked that deserve honest answers.",
            reversedMeaning: "Intelligence is being used for gossip, manipulation, or needless confrontation. The sharp mind has been put in service of mischief rather than truth. Or, brilliant ideas are being hoarded rather than shared — the sword sheathed when it should be raised.",
            keywords: ["curiosity", "intelligence", "news", "mental agility"],
            symbolism: "A nimble youth on a blustery hilltop raises a sword to the sky — testing the blade against the wind's resistance.",
            symbolName: "wind"),
        TarotCard(id: 61, name: "Knight of Swords", arcana: .minor, suit: .swords, number: "Knight",
            uprightMeaning: "A fully armored knight charges at full gallop through a windswept landscape, sword raised, neither looking left nor right. The Knight of Swords is pure forward momentum — brilliant, decisive, unstoppable, and occasionally oblivious to the collateral of his passage. Speed is the gift; discernment must be cultivated.",
            reversedMeaning: "Aggression without cause, or a charge that has been derailed by obstacles creating frustration and erratic behaviour. The knight has crashed and must regroup before charging again. Or, the gift of decisiveness has been lost to paralysis and second-guessing.",
            keywords: ["ambition", "directness", "communication", "charging forward"],
            symbolism: "An armored knight rides at full charge across a storm-bent landscape, every element of horse and rider directed toward a single invisible target.",
            symbolName: "wind"),
        TarotCard(id: 62, name: "Queen of Swords", arcana: .minor, suit: .swords, number: "Queen",
            uprightMeaning: "She sits in clear air above the clouds, one hand extended in greeting, one holding her sword upright. She has known loss and grief, and those experiences have made her not hard but precise. The Queen of Swords sees through nonsense with surgical grace, and her clarity is a gift even when its delivery stings.",
            reversedMeaning: "Pain has hardened into coldness, or bitterness is sharpening the blade past the point of discernment into cruelty. The Queen's clear sight has become a weapon rather than an offering. Alternatively, necessary directness is being suppressed from fear of confrontation.",
            keywords: ["clear communication", "independence", "perception", "truth"],
            symbolism: "A crowned queen sits with upraised sword above the stormclouds, butterflies on her crown, one hand extended in the gesture of honest welcome.",
            symbolName: "wind"),
        TarotCard(id: 63, name: "King of Swords", arcana: .minor, suit: .swords, number: "King",
            uprightMeaning: "The master of intellect sits upright on his stone throne, sword aimed at the sky, butterflies of transformation behind him. The King of Swords is the judge, the analyst, the one who makes difficult decisions from a place of principle rather than preference. His is the gift of fair, unyielding clarity.",
            reversedMeaning: "Intellect has become tyranny. Decisions are being made from cold logic that ignores human cost, or power is being abused through manipulation and legal maneuvering. The mind that should serve truth is serving ego instead.",
            keywords: ["intellectual authority", "ethics", "judgment", "truth"],
            symbolism: "An authoritative king holds his sword straight to the sky, cloud and wind around him but his gaze and his aim undeviating.",
            symbolName: "wind")
    ]

    // MARK: Minor Arcana — Pentacles (14 cards)
    static let minorArcanaPentacles: [TarotCard] = [
        TarotCard(id: 64, name: "Ace of Pentacles", arcana: .minor, suit: .pentacles, number: "Ace",
            uprightMeaning: "A hand from the clouds offers a golden pentacle above a garden archway opening onto fertile land. This is the seed of material manifestation — the beginning of financial opportunity, physical security, or a new endeavour rooted in the real world. The gift is being offered. Will you take it and plant it?",
            reversedMeaning: "A material opportunity is being missed, or greed and shortsightedness are preventing the proper reception of what is being offered. The seed has fallen on concrete rather than earth. The foundation needs tending before the building can begin.",
            keywords: ["opportunity", "material beginnings", "security", "abundance"],
            symbolism: "A divine hand extends a gleaming pentacle through a garden archway toward a landscape of cultivated abundance.",
            symbolName: "leaf.fill"),
        TarotCard(id: 65, name: "Two of Pentacles", arcana: .minor, suit: .pentacles, number: "2",
            uprightMeaning: "A figure juggles two pentacles within an infinity loop while ships toss on waves behind him — yet he manages with grace. The Two of Pentacles is the art of managing competing demands with fluid adaptability. Life is multitasking; the question is whether you are dancing with it or fighting it.",
            reversedMeaning: "The juggling act has become overwhelming and something is about to drop. Financial decisions need more careful attention. The carefree dance has become a desperate scramble — it is time to prioritise, simplify, and set down what is not essential.",
            keywords: ["balance", "adaptability", "time management", "flexibility"],
            symbolism: "A dancer juggling two pentacles connected by an infinity loop, ships negotiating waves in the background.",
            symbolName: "leaf.fill"),
        TarotCard(id: 66, name: "Three of Pentacles", arcana: .minor, suit: .pentacles, number: "3",
            uprightMeaning: "An artisan works on a cathedral while an architect and monk review the plans. The Three of Pentacles is the magic of skilled collaboration — of bringing different kinds of expertise into dialogue in service of something larger than any one person could build. Excellence is a team effort.",
            reversedMeaning: "Collaboration has broken down due to ego, poor communication, or a misalignment of vision. Work is being done in isolation when it should be collective, or mediocrity is being accepted to avoid the friction of high standards. The cathedral is being built crooked.",
            keywords: ["teamwork", "craftsmanship", "collaboration", "mastery"],
            symbolism: "A craftsman works on stone carvings in a cathedral while two advisors consult architectural plans — expertise in conversation.",
            symbolName: "leaf.fill"),
        TarotCard(id: 67, name: "Four of Pentacles", arcana: .minor, suit: .pentacles, number: "4",
            uprightMeaning: "A crowned figure holds one pentacle to his chest, one under each foot, one balanced on his head — gripping his material security with every available surface of his body. The Four of Pentacles asks what you are holding so tightly that nothing new can enter your hands. Stability is good; hoarding keeps the river from flowing.",
            reversedMeaning: "The grip is loosening. Either generosity and a healthier relationship with material security is emerging, or financial recklessness has been freed from the constraint of sensible caution. Find the middle point between the miser and the spendthrift.",
            keywords: ["security", "control", "scarcity", "possessiveness"],
            symbolism: "A crowned figure clutches a pentacle to his heart, another under each foot, one balanced on his head — total physical possession.",
            symbolName: "leaf.fill"),
        TarotCard(id: 68, name: "Five of Pentacles", arcana: .minor, suit: .pentacles, number: "5",
            uprightMeaning: "Two impoverished figures walk through snow beneath a warmly lit church window. The Five of Pentacles speaks of material hardship, poverty, or the feeling of being left out in the cold — but the light in the window above them goes unnoticed. Help is often closer than it appears. Pride can be as isolating as poverty.",
            reversedMeaning: "Recovery from hardship is beginning. Material conditions are improving, or the willingness to ask for help is returning after a period of proud suffering. The door of the church has been found; the threshold can now be crossed.",
            keywords: ["hardship", "financial struggle", "poverty", "isolation"],
            symbolism: "Two cloaked figures hobble through snow past a lit stained-glass window, too cold and low to see the warmth available above them.",
            symbolName: "leaf.fill"),
        TarotCard(id: 69, name: "Six of Pentacles", arcana: .minor, suit: .pentacles, number: "6",
            uprightMeaning: "A wealthy merchant with balanced scales distributes coins to kneeling beggars. The Six of Pentacles is the card of generosity and fair exchange — of giving and receiving in right proportion. Resources are flowing; the question is whether you are in the role of giver, receiver, or the scale itself.",
            reversedMeaning: "An imbalance of giving and receiving. Either generosity has strings attached and functions as control, or receiving is tinged with resentment and loss of dignity. True exchange requires that both parties maintain their wholeness in the transaction.",
            keywords: ["generosity", "charity", "giving and receiving", "fairness"],
            symbolism: "A prosperous merchant holds balanced scales and distributes coins to two kneeling figures — the circulation of wealth in right measure.",
            symbolName: "leaf.fill"),
        TarotCard(id: 70, name: "Seven of Pentacles", arcana: .minor, suit: .pentacles, number: "7",
            uprightMeaning: "A farmer leans on his hoe and contemplates the seven pentacles growing on the bush he has been tending. The Seven of Pentacles is the mid-point assessment — the pause in the middle of the long work to evaluate whether the effort is yielding the expected fruit. Patience and honest evaluation are both required.",
            reversedMeaning: "Impatience or misaligned effort is threatening the harvest. Either you are abandoning what you planted before it had time to mature, or you are pouring energy into something that genuinely will not yield what you hoped. Discernment between patience and delusion is the task.",
            keywords: ["patience", "investment", "assessment", "long-term vision"],
            symbolism: "A weary farmer leans on his hoe and studies the seven pentacle-fruits growing from the bush of his long labour.",
            symbolName: "leaf.fill"),
        TarotCard(id: 71, name: "Eight of Pentacles", arcana: .minor, suit: .pentacles, number: "8",
            uprightMeaning: "A young craftsman carves pentacles with total absorption, six finished on a pole beside him, two more to complete. The Eight of Pentacles is the deep satisfaction of skilled work — of becoming excellent through the practice of the same thing many times until mastery emerges almost without noticing. Dedication is its own reward.",
            reversedMeaning: "Perfectionism has stalled productivity, or work is being performed mechanically without the engaged attention that produces quality. Either the standards have become unreachable, or the work has become disconnected from meaning. Find the joy in the making again.",
            keywords: ["diligence", "craftsmanship", "skill development", "mastery"],
            symbolism: "A focused craftsman carves pentacle after pentacle at his bench, surrounded by evidence of his patient, accumulating skill.",
            symbolName: "leaf.fill"),
        TarotCard(id: 72, name: "Nine of Pentacles", arcana: .minor, suit: .pentacles, number: "9",
            uprightMeaning: "A woman in a golden vineyard with a falcon on her gloved wrist walks among her abundance with complete poise and independence. The Nine of Pentacles is the achievement of material self-sufficiency — the elegant enjoyment of what has been created through one's own sustained effort. You have earned this.",
            reversedMeaning: "Financial independence is being undermined by dependency, poor decisions, or the substitution of material comfort for genuine fulfilment. The garden is beautiful, but something essential is absent. What has been sacrificed in the pursuit of security?",
            keywords: ["abundance", "self-sufficiency", "independence", "luxury"],
            symbolism: "A poised woman strolls a private vineyard with a trained falcon — the picture of graceful, self-made abundance.",
            symbolName: "leaf.fill"),
        TarotCard(id: 73, name: "Ten of Pentacles", arcana: .minor, suit: .pentacles, number: "10",
            uprightMeaning: "An old patriarch in a patterned robe sits beneath a decorated archway, grandchildren at play, dogs at his feet, his adult children behind him. The Ten of Pentacles is legacy — the material and spiritual wealth that extends across generations, the sense of having built something that will outlast you.",
            reversedMeaning: "Family conflict over money or legacy is creating instability. The structure of material security has cracks — either in the foundation or in the relationships that hold it. What has been built together is being pulled apart by competing claims or unspoken resentments.",
            keywords: ["legacy", "family wealth", "stability", "inheritance"],
            symbolism: "An elder surrounded by grandchildren and dogs sits beneath an archway of coins — the portrait of a life that has made itself permanent.",
            symbolName: "leaf.fill"),
        TarotCard(id: 74, name: "Page of Pentacles", arcana: .minor, suit: .pentacles, number: "Page",
            uprightMeaning: "A young figure in a green field holds up a pentacle and studies it with complete concentration. The Page of Pentacles is the student of the material world — earnest, methodical, and deeply interested in how things actually work. This is the energy of new skills being learned with genuine seriousness.",
            reversedMeaning: "Lack of focus or follow-through on practical matters. Interesting ideas remain perpetually at the study stage, never reaching the execution phase. Or, materialism without wisdom — the interest in wealth without the values that would make that wealth meaningful.",
            keywords: ["studiousness", "ambition", "new skills", "practicality"],
            symbolism: "A contemplative youth in a blooming field holds a pentacle aloft, studying it with the complete attention of a first encounter.",
            symbolName: "leaf.fill"),
        TarotCard(id: 75, name: "Knight of Pentacles", arcana: .minor, suit: .pentacles, number: "Knight",
            uprightMeaning: "A fully armed knight sits on a dark horse in a cultivated field, holding a pentacle and surveying the terrain with patient deliberation. Unlike the other knights, he is entirely still — because he knows that this ground requires not speed but steadiness. Methodical progress is his gift and his power.",
            reversedMeaning: "Stubbornness masquerades as steadiness, or the methodical approach has become stuck in the mud of routine. The responsible work ethic has calcified into a refusal to adapt. Something new is being resisted not from wisdom but from inertia.",
            keywords: ["reliability", "persistence", "efficiency", "conservatism"],
            symbolism: "A dark-armored knight sits perfectly still on a powerful horse in a tilled field, holding a single pentacle with total attentiveness.",
            symbolName: "leaf.fill"),
        TarotCard(id: 76, name: "Queen of Pentacles", arcana: .minor, suit: .pentacles, number: "Queen",
            uprightMeaning: "She sits on a flower-carved throne in a green bower with a rabbit at her feet, cradling a pentacle in her lap with the ease of long familiarity. The Queen of Pentacles has created a world of practical abundance — a home that nourishes, a life that sustains, a generosity that flows from her own deep rootedness in what actually matters.",
            reversedMeaning: "Over-focus on material security at the expense of emotional or spiritual nourishment, or the practical care has become suffocating control. Alternatively, financial mismanagement or neglect of the material dimension of life is creating instability.",
            keywords: ["nurturing", "practical", "resourceful", "grounded"],
            symbolism: "A richly robed queen cradles a golden pentacle in her lush garden throne while a nimble hare keeps her company.",
            symbolName: "leaf.fill"),
        TarotCard(id: 77, name: "King of Pentacles", arcana: .minor, suit: .pentacles, number: "King",
            uprightMeaning: "A king enthroned in a garden overgrown with vines and grapes, his armor covered with bull motifs, a scepter in one hand and a pentacle in the other. The King of Pentacles has built a kingdom on the patient accumulation of real value — he is the master of the material world because he has respected it, not exploited it.",
            reversedMeaning: "Materialism without wisdom, or the misuse of accumulated power. Financial stubbornness is creating problems, or wealth is being used to control others. The king who confuses his kingdom for himself has already begun the process of losing both.",
            keywords: ["financial mastery", "abundance", "reliability", "security"],
            symbolism: "A powerful king seated in a castle garden, his every surface adorned with the symbols of abundance — vines, bulls, pentacles, and gold.",
            symbolName: "leaf.fill")
    ]
}
